/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminOffersRouteImport } from './routes/admin.offers'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as ProductsAccessoriesRouteImport } from './routes/products.accessories'
import { Route as ProductsEvRouteImport } from './routes/products.ev'
import { Route as ProductsLubesRouteImport } from './routes/products.lubes'
import { Route as ResourcesVideoGalleryRouteImport } from './routes/resources.video-gallery'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesSlugRouteImport } from './routes/vehicles.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsAccessoriesRoute = ProductsAccessoriesRouteImport.update({
  id: '/products/accessories',
  path: '/products/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsEvRoute = ProductsEvRouteImport.update({
  id: '/products/ev',
  path: '/products/ev',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsLubesRoute = ProductsLubesRouteImport.update({
  id: '/products/lubes',
  path: '/products/lubes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesVideoGalleryRoute = ResourcesVideoGalleryRouteImport.update({
  id: '/resources/video-gallery',
  path: '/resources/video-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesSlugRoute = VehiclesSlugRouteImport.update({
  id: '/vehicles/$slug',
  path: '/vehicles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/ev': typeof ProductsEvRoute
  '/products/lubes': typeof ProductsLubesRoute
  '/resources/video-gallery': typeof ResourcesVideoGalleryRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/ev': typeof ProductsEvRoute
  '/products/lubes': typeof ProductsLubesRoute
  '/resources/video-gallery': typeof ResourcesVideoGalleryRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/vehicles': typeof VehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/vehicles': typeof AdminVehiclesRoute
  '/products/accessories': typeof ProductsAccessoriesRoute
  '/products/ev': typeof ProductsEvRoute
  '/products/lubes': typeof ProductsLubesRoute
  '/resources/video-gallery': typeof ResourcesVideoGalleryRoute
  '/vehicles/$slug': typeof VehiclesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/vehicles/': typeof VehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/offers'
    | '/admin/enquiries'
    | '/admin/offers'
    | '/admin/vehicles'
    | '/products/accessories'
    | '/products/ev'
    | '/products/lubes'
    | '/resources/video-gallery'
    | '/vehicles/$slug'
    | '/admin/'
    | '/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/offers'
    | '/admin/enquiries'
    | '/admin/offers'
    | '/admin/vehicles'
    | '/products/accessories'
    | '/products/ev'
    | '/products/lubes'
    | '/resources/video-gallery'
    | '/vehicles/$slug'
    | '/admin'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/offers'
    | '/admin/enquiries'
    | '/admin/offers'
    | '/admin/vehicles'
    | '/products/accessories'
    | '/products/ev'
    | '/products/lubes'
    | '/resources/video-gallery'
    | '/vehicles/$slug'
    | '/admin/'
    | '/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  OffersRoute: typeof OffersRoute
  ProductsAccessoriesRoute: typeof ProductsAccessoriesRoute
  ProductsEvRoute: typeof ProductsEvRoute
  ProductsLubesRoute: typeof ProductsLubesRoute
  ResourcesVideoGalleryRoute: typeof ResourcesVideoGalleryRoute
  VehiclesSlugRoute: typeof VehiclesSlugRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/accessories': {
      id: '/products/accessories'
      path: '/products/accessories'
      fullPath: '/products/accessories'
      preLoaderRoute: typeof ProductsAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/ev': {
      id: '/products/ev'
      path: '/products/ev'
      fullPath: '/products/ev'
      preLoaderRoute: typeof ProductsEvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/lubes': {
      id: '/products/lubes'
      path: '/products/lubes'
      fullPath: '/products/lubes'
      preLoaderRoute: typeof ProductsLubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/video-gallery': {
      id: '/resources/video-gallery'
      path: '/resources/video-gallery'
      fullPath: '/resources/video-gallery'
      preLoaderRoute: typeof ResourcesVideoGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$slug': {
      id: '/vehicles/$slug'
      path: '/vehicles/$slug'
      fullPath: '/vehicles/$slug'
      preLoaderRoute: typeof VehiclesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminVehiclesRoute: typeof AdminVehiclesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminVehiclesRoute: AdminVehiclesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  OffersRoute: OffersRoute,
  ProductsAccessoriesRoute: ProductsAccessoriesRoute,
  ProductsEvRoute: ProductsEvRoute,
  ProductsLubesRoute: ProductsLubesRoute,
  ResourcesVideoGalleryRoute: ResourcesVideoGalleryRoute,
  VehiclesSlugRoute: VehiclesSlugRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
